services:
  mailpit:
    image: axllent/mailpit:latest
    container_name: interviewer_ai_mailpit_dev
    restart: unless-stopped
    ports:
      - "127.0.0.1:1025:1025"
      - "127.0.0.1:8025:8025"
    networks:
      - interviewer_ai_network

  postgres:
    image: postgres:18.1-alpine3.22
    container_name: interviewer_ai_pg_dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${PG_USER:-interviewer_ai_dev_user}
      POSTGRES_PASSWORD: ${PG_PASSWORD:-interviewer_ai_dev_pass}
      POSTGRES_DB: ${PG_DB:-interviewer_ai_dev_db}
    ports:
      - "127.0.0.1:${PG_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${PG_USER:-interviewer_ai_dev_user} -d ${PG_DB:-interviewer_ai_dev_db}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - interviewer_ai_network

  pgadmin:
    image: dpage/pgadmin4:9.8
    container_name: interviewer_ai_pgadmin_dev
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "127.0.0.1:8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: demo@example.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    configs:
      - source: pgadmin-servers
        target: /pgadmin4/servers.json
        mode: 0444
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - interviewer_ai_network

configs:
  pgadmin-servers:
    content: |
      {
        "Servers": {
          "1": {
            "Name": "Local Postgres",
            "Group": "Servers",
            "Host": "postgres",
            "Port": 5432,
            "MaintenanceDB": "interviewer_ai_dev_db",
            "Username": "interviewer_ai_dev_user",
            "Password": "interviewer_ai_dev_pass"
          }
        }
      }

volumes:
  postgres_data:
  pgadmin_data:

networks:
  interviewer_ai_network:
    driver: bridge
