ALTER TABLE "coding_problems"
ADD COLUMN "topics" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "companies" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "hint" TEXT,
ADD COLUMN "is_premium" BOOLEAN NOT NULL DEFAULT false;
